### ISSUE TITLE
Unable to build on windows with msvc

### ISSUE THREAD

**Issue by synodriver** [lz1998/silk-rs#1]
warning: couldn't execute `llvm-config --prefix` (error: program not found)
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

error: failed to run custom build command for `silk-rs v0.1.0 (https://github.com/lz1998/silk-rs?branch=main#3951ee61)`

Caused by:
  process didn't exit successfully: `F:\pyproject\rsilk\target\debug\build\silk-rs-19638ae05635062f\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (i
nvalid: [])"', C:\Users\LAB\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.3\src/lib.rs:1956:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: cargo failed with code: 101

**Comment by niuhuan** [comment]
Install llvm before cargo build. 

Download the llvm release name same as LLVM-${version}-win64.exe from https://github.com/llvm/llvm-project/releases/ 

![20220321183139](https://user-images.githubusercontent.com/20847533/159244130-eaf1ac28-5e46-4929-8310-477d45b48dcf.png)

**Comment by synodriver** [comment]
Thanks. Have fixed it using github action.
